overwrite: true
schema: "https://beatminesweeper.app/graphql"
documents: "ts-src/graphql/**/*.graphql"
generates:
  ts-src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
